### ISSUE TITLE
New component model gives two sets of platforms.. needs fixing

### ISSUE THREAD

**Issue by asantaga** [asantaga/lightwaverf_HA_EnergySensor#3]
New model for some reason gives to sets of sensors.. not sure why

@matthewjporter :  Any chance you can checkout code in branch ```MigrateComponnetToNewModel``` and see if it works for you?

**Comment by matthewjporter** [comment]
@asantaga tested and still working, only getting one set of sensors so right now looks good my side

**Comment by asantaga** [comment]
Awesome, as soon as I fix the "default value thing" in issue 4 then I'll restart the publishing process (they rejected it because it was using the old component style ) :-(
