### ISSUE TITLE
How to open ports on HASS.io on raspbery pi 4

### ISSUE THREAD

**Issue by gshoebridge** [asantaga/lightwaverf_HA_EnergySensor#6]
I have HASS running on a Pi4 - what is the instruction to open the following?

Ensure port 9761/UDP is open on your linux server.

Thanks

**Comment by asantaga** [comment]
Alas I dont have a RPI to test this out, but I think ootb the raspberry pi doesnt have a pre installed firewall.. it might just work.

try it first.. 

if you want to install a firewall try ufw, See this link for details
https://www.raspberrypi.org/documentation/configuration/security.md

**Comment by gshoebridge** [comment]
Many thanks

Where I have the problem is that the integration just doesn't appear to work and if pi doesn't have a firewall then it should without issue

I was wondering whether this was working with other RPI users using the HASS OS.
Alternatively I'm thinking about moving to LWave2 so it may become irrelevant

Guy Shoebridge
Service Delivery Manager
Ultima Business Solutions Ltd

________________________________

**Comment by asantaga** [comment]
other users are using it but yes "the network" does cause issues.. its not that the integration doesnt work (although of course Id say that :-)  ) but you need to make sure your on the same subnet etc otherwise the udp packets dont get through..

Can you connect your RPI to the same router/switch as the smartlink box?

**Comment by asantaga** [comment]
Checkout this github gist, it basically displays all the data the RPI is receiving on the right port, it waits up to 30 seconds (ignore the comment) for data.. 

https://gist.github.com/asantaga/308f3a2fc59172e9f272d52a29a25e5b
